### ISSUE TITLE
missing lines and arrows

### ISSUE THREAD

**Issue by redFrik** [blacksound/ClassInfo#1]
resulting dot and pdf files only show boxes - no connections :-(

```Class.makeUMLForClasses(UGen.subclasses, "~/Desktop/dump/UGen".standardizePath)```

```
dot - graphviz version 2.43.0 (0)
libdir = "/usr/local/Cellar/graphviz/2.42.2/lib/graphviz"
Activated plugin library: libgvplugin_dot_layout.6.dylib
Using layout: dot:dot_layout
Activated plugin library: libgvplugin_core.6.dylib
Using render: dot:core
Using device: dot:dot:core
The plugin configuration file:
	/usr/local/Cellar/graphviz/2.42.2/lib/graphviz/config6
		was successfully loaded.
```

macOS 10.12.6, sc3.10.3

**Comment by salkin-mada** [comment]
I seems that with direct usage of .makeUMLForClasses this will never be true: `if(classes.includes(class.superclass)` in the makeDotfileStringForClasses method.

try to use `UGen.makeUML("~/Desktop/dump/ugens".standardizePath)` this should give you text, boxes and connections

@redFrik
> resulting dot and pdf files only show boxes - no connections :-(
> 
> `Class.makeUMLForClasses(UGen.subclasses, "~/Desktop/dump/UGen".standardizePath)`

**Comment by redFrik** [comment]
thanks @salkin-mada, now i got 'em lines.
had to set the second argument to true though to get subclasses and generate some connections...
```UGen.makeUML("~/Desktop/dump/ugens".standardizePath, true)```
happy happy.
